services:

  postgres:
    image: postgres:16
    container_name: postgres

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  cube:
    image: cubejs/cube:latest
    container_name: cube

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "4000:4000"

    volumes:
      - ./cube:/cube/conf

volumes:
  postgres_data: